
package agence.web.reservationWS;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExceptionGetReference", targetNamespace = "http://services.service.web.hotel/")
public class ExceptionGetReference_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionGetReference faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionGetReference_Exception(String message, ExceptionGetReference faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExceptionGetReference_Exception(String message, ExceptionGetReference faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: agence.web.reservationWS.ExceptionGetReference
     */
    public ExceptionGetReference getFaultInfo() {
        return faultInfo;
    }

}
