
package agence.web.consultationWS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelServiceConsult", targetNamespace = "http://services.service.web.hotel/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelServiceConsult {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.util.List<agence.web.consultationWS.Offre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeOffres", targetNamespace = "http://services.service.web.hotel/", className = "agence.web.consultationWS.GetListeOffres")
    @ResponseWrapper(localName = "getListeOffresResponse", targetNamespace = "http://services.service.web.hotel/", className = "agence.web.consultationWS.GetListeOffresResponse")
    @Action(input = "http://services.service.web.hotel/IHotelServiceConsult/getListeOffresRequest", output = "http://services.service.web.hotel/IHotelServiceConsult/getListeOffresResponse")
    public List<Offre> getListeOffres(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7);

    /**
     * 
     * @return
     *     returns java.util.List<agence.web.consultationWS.Hotel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHotelsService", targetNamespace = "http://services.service.web.hotel/", className = "agence.web.consultationWS.GetHotelsService")
    @ResponseWrapper(localName = "getHotelsServiceResponse", targetNamespace = "http://services.service.web.hotel/", className = "agence.web.consultationWS.GetHotelsServiceResponse")
    @Action(input = "http://services.service.web.hotel/IHotelServiceConsult/getHotelsServiceRequest", output = "http://services.service.web.hotel/IHotelServiceConsult/getHotelsServiceResponse")
    public List<Hotel> getHotelsService();

}
