
package client.consumer.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgenceServiceUtilisateurImplService", targetNamespace = "http://client.service.web.agence/", wsdlLocation = "http://localhost:8088/agencewebservice?wsdl")
public class AgenceServiceUtilisateurImplService
    extends Service
{

    private final static URL AGENCESERVICEUTILISATEURIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGENCESERVICEUTILISATEURIMPLSERVICE_EXCEPTION;
    private final static QName AGENCESERVICEUTILISATEURIMPLSERVICE_QNAME = new QName("http://client.service.web.agence/", "AgenceServiceUtilisateurImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/agencewebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCESERVICEUTILISATEURIMPLSERVICE_WSDL_LOCATION = url;
        AGENCESERVICEUTILISATEURIMPLSERVICE_EXCEPTION = e;
    }

    public AgenceServiceUtilisateurImplService() {
        super(__getWsdlLocation(), AGENCESERVICEUTILISATEURIMPLSERVICE_QNAME);
    }

    public AgenceServiceUtilisateurImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCESERVICEUTILISATEURIMPLSERVICE_QNAME, features);
    }

    public AgenceServiceUtilisateurImplService(URL wsdlLocation) {
        super(wsdlLocation, AGENCESERVICEUTILISATEURIMPLSERVICE_QNAME);
    }

    public AgenceServiceUtilisateurImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCESERVICEUTILISATEURIMPLSERVICE_QNAME, features);
    }

    public AgenceServiceUtilisateurImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgenceServiceUtilisateurImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAgenceServiceUtilisateur
     */
    @WebEndpoint(name = "AgenceServiceUtilisateurImplPort")
    public IAgenceServiceUtilisateur getAgenceServiceUtilisateurImplPort() {
        return super.getPort(new QName("http://client.service.web.agence/", "AgenceServiceUtilisateurImplPort"), IAgenceServiceUtilisateur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAgenceServiceUtilisateur
     */
    @WebEndpoint(name = "AgenceServiceUtilisateurImplPort")
    public IAgenceServiceUtilisateur getAgenceServiceUtilisateurImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.service.web.agence/", "AgenceServiceUtilisateurImplPort"), IAgenceServiceUtilisateur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCESERVICEUTILISATEURIMPLSERVICE_EXCEPTION!= null) {
            throw AGENCESERVICEUTILISATEURIMPLSERVICE_EXCEPTION;
        }
        return AGENCESERVICEUTILISATEURIMPLSERVICE_WSDL_LOCATION;
    }

}
