
package client.consumer.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExceptionGetReference", targetNamespace = "http://services.service.web.hotel/")
public class ExceptionGetReferenceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionGetReference faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionGetReferenceException(String message, ExceptionGetReference faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExceptionGetReferenceException(String message, ExceptionGetReference faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.consumer.service.ExceptionGetReference
     */
    public ExceptionGetReference getFaultInfo() {
        return faultInfo;
    }

}
