
package client.consumer.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAgenceServiceUtilisateur", targetNamespace = "http://client.service.web.agence/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAgenceServiceUtilisateur {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.util.List<client.consumer.service.Offre>
     * @throws DatatypeConfigurationException_Exception
     */
    @WebMethod(operationName = "ConsultationOffre")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsultationOffre", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.ConsultationOffre")
    @ResponseWrapper(localName = "ConsultationOffreResponse", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.ConsultationOffreResponse")
    @Action(input = "http://client.service.web.agence/IAgenceServiceUtilisateur/ConsultationOffreRequest", output = "http://client.service.web.agence/IAgenceServiceUtilisateur/ConsultationOffreResponse", fault = {
        @FaultAction(className = DatatypeConfigurationException_Exception.class, value = "http://client.service.web.agence/IAgenceServiceUtilisateur/ConsultationOffre/Fault/DatatypeConfigurationException")
    })
    public List<Offre> consultationOffre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6)
        throws DatatypeConfigurationException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     * @throws ExceptionGetReferenceException
     * @throws DatatypeConfigurationException_Exception
     * @throws ParseException_Exception
     */
    @WebMethod(operationName = "Reservation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reservation", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.Reservation")
    @ResponseWrapper(localName = "ReservationResponse", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.ReservationResponse")
    @Action(input = "http://client.service.web.agence/IAgenceServiceUtilisateur/ReservationRequest", output = "http://client.service.web.agence/IAgenceServiceUtilisateur/ReservationResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://client.service.web.agence/IAgenceServiceUtilisateur/Reservation/Fault/ParseException"),
        @FaultAction(className = DatatypeConfigurationException_Exception.class, value = "http://client.service.web.agence/IAgenceServiceUtilisateur/Reservation/Fault/DatatypeConfigurationException"),
        @FaultAction(className = ExceptionGetReferenceException.class, value = "http://client.service.web.agence/IAgenceServiceUtilisateur/Reservation/Fault/ExceptionGetReference_Exception")
    })
    public float reservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        InfosPersonnes arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4)
        throws DatatypeConfigurationException_Exception, ExceptionGetReferenceException, ParseException_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReferenceResa", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.GetReferenceResa")
    @ResponseWrapper(localName = "getReferenceResaResponse", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.GetReferenceResaResponse")
    @Action(input = "http://client.service.web.agence/IAgenceServiceUtilisateur/getReferenceResaRequest", output = "http://client.service.web.agence/IAgenceServiceUtilisateur/getReferenceResaResponse")
    public int getReferenceResa();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgenceNames", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.GetAgenceNames")
    @ResponseWrapper(localName = "getAgenceNamesResponse", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.GetAgenceNamesResponse")
    @Action(input = "http://client.service.web.agence/IAgenceServiceUtilisateur/getAgenceNamesRequest", output = "http://client.service.web.agence/IAgenceServiceUtilisateur/getAgenceNamesResponse")
    public List<String> getAgenceNames();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImageURL", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.GetImageURL")
    @ResponseWrapper(localName = "getImageURLResponse", targetNamespace = "http://client.service.web.agence/", className = "client.consumer.service.GetImageURLResponse")
    @Action(input = "http://client.service.web.agence/IAgenceServiceUtilisateur/getImageURLRequest", output = "http://client.service.web.agence/IAgenceServiceUtilisateur/getImageURLResponse")
    public String getImageURL(
        @WebParam(name = "arg0", targetNamespace = "")
        Offre arg0);

}
